;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @sfx_ntsc_0, @sfx_pal_0
	.word @sfx_ntsc_1, @sfx_pal_1
	.word @sfx_ntsc_2, @sfx_pal_2


@sfx_ntsc_0:
	.byte $80,$3e,$81,$93,$82,$01,$01,$80,$3c,$01,$80,$3a,$01,$80,$38,$01
	.byte $80,$36,$01,$80,$35,$1f,$00
@sfx_pal_0:
	.byte $80,$3e,$81,$76,$82,$01,$01,$80,$3c,$01,$80,$3a,$01,$80,$38,$01
	.byte $80,$36,$01,$80,$35,$19,$00
@sfx_ntsc_1:
	.byte $89,$3e,$8a,$0b,$01,$89,$3c,$01,$89,$3a,$01,$89,$38,$01,$89,$36
	.byte $01,$89,$35,$07,$00
@sfx_pal_1:
	.byte $89,$3e,$8a,$0b,$01,$89,$3c,$01,$89,$3a,$01,$89,$38,$01,$89,$36
	.byte $01,$89,$35,$05,$00
@sfx_ntsc_2:
	.byte $86,$81,$87,$52,$88,$01,$0c,$00
@sfx_pal_2:
	.byte $86,$81,$87,$3a,$88,$01,$0a,$00
